### ISSUE TITLE
getUser() Method is returning empty

### ISSUE THREAD

**Issue by tonixx** [jcleblanc/reddit-php-sdk#25]
When I try to login, I'm taken to Reddit, asked for permissions, I click on Accept and then I'm  taken to my PHP file where I'm trying to display user info but nothing is shown. Here's the code:

<?
error_reporting(E_ALL);

require_once("reddit.php");
$reddit = new reddit();

$userData = $reddit->getUser();

print_r($userData);
?>

You can test it here: http://alienreader.com/login2.php

Any help would be great. Thx in advance!

**Comment by SquareWheel** [comment]
I have the same problem as above.  Randomly when contacting reddit the page will take much longer to load, and then getUser() returns empty.  At the moment this is happening in ~1/5 page loads.

Is this an issue on reddit's side and there's nothing we can do about it?  It's unfortunately a pretty major deterrent to using reddit's API.
