### ISSUE TITLE
is it possible to disable oauth?

### ISSUE THREAD

**Issue by vesper8** [jcleblanc/reddit-php-sdk#49]
Just wondering.. I was previously using another api wrapper found on github but I like the simplicity of yours better.. however I only mean to use it to make calls that aren't in the context of a logged in user.. such as searching for new/hot/trending posts in various subreddits. I understand you can make these without oauth as I was just making them. I understand oauth allows for higher rate limits but the non-oauth ones are ok for my current uses. I did get yours working with oauth but it's adding a layer of complexity and if there's an easy way to do without it and go back to non-oauth api calls (for those that allow it) then I'd like to know how.

Oh and.. I know some people don't like composer for some reason but.. well I do so if you ever decide to add your awesome project to composer you'll make me and some others happy I guess.

Lastly.. any chance you can use an array instead of constants in your config.php? Not a fan of constants especially those with common names as they can easily create conflicts in a big application.

Thanks and keep up the fine work!

**Comment by jcleblanc** [comment]
Based on current standards, this is no longer an option
