### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by ioudas210** [jcleblanc/reddit-php-sdk#53]
This software does not work with reddit so far. Just returns null when trying any of the listed calls in documentation.

**Comment by neatville** [comment]
Since there are steps to take on the Reddit website when logged in, I think there should be some tutorial on what exactly to put in those fields (not that there isn't.)

**Comment by jcleblanc** [comment]
OAuth functionality has been restored, so the endpoints should work with the new edit. This required an SSL version bump.
