### ISSUE TITLE
How do I retrieve frontpage data?

### ISSUE THREAD

**Issue by samslate2** [jcleblanc/reddit-php-sdk#57]
what's the equivalent to "https://www.reddit.com/.json" here for authenticated users?

**Comment by samslate2** [comment]
I'm baffled by its omission, but here:

```public function frontpage(){```
```$urlListing = "{$this->apiHost}/.json";```
```return self::runCurl($urlListing);}```


this *usually* returns the front page of reddit... aka *the front page of the internet*... I'm really scratching my head as to why this isn't included in reddit.php by default...

**Comment by jcleblanc** [comment]
It is, in getListing()
