### ISSUE TITLE
Result of functions are always NULL

### ISSUE THREAD

**Issue by Proliner** [jcleblanc/reddit-php-sdk#58]
```
<?php

require_once 'reddit.php';

$reddit = new reddit();
$userData = $reddit->getUser();

$response = $reddit->getListing("technology", 5);

var_dump($userData);
var_dump($response);

?>
```

And whatever I do, my result is always NULL. Can someone explain to me what I do wrong here, please?

**Comment by farmnick** [comment]
I'm having this exact same problem. I've been extremely frustrated and have been attempting to find a solution for days.

**Comment by Proliner** [comment]
@farmnick There are more reddit php bot scripts here on Github.

**Comment by jcleblanc** [comment]
OAuth functionality has been restored, so the endpoints should work with the new edit. This required an SSL version bump.
