### ISSUE TITLE
Please deprecate this project and remove it from the list of suggested Reddit API Wrappers

### ISSUE THREAD

**Issue by LukeNZ** [jcleblanc/reddit-php-sdk#60]
After days of trying to get this to work, I've given up. This code base is either broken or faulty, and all calls return 403. The repository owner appears to have abandoned this project.

**Comment by kevineger** [comment]
@LukeNZ Yeah I can't seem to get it to work either. Have you come across any other alternatives for php reddit API wrappers?

**Comment by LukeNZ** [comment]
@kevineger Hey Kevin,

It may not be of much use to you, but I ended up writing my own API wrapper for Reddit [here](https://github.com/LukeNZ/phpreddit). I wouldn't recommend using it (although the two API endpoints I ended up needing are indeed working), but if you fork it/browse the source code, you should be able to understand the concept well enough to write your own methods for whatever endpoints need accessing.

Only dependency is Guzzle 6 to make the HTTP requests to Reddit. If you do decide to use it, I've also published it to [packagist here](https://packagist.org/packages/luke-nz/phpreddit). Simply require in:

    "luke-nz/phpreddit": "dev-master@dev"

into your `composer.json` file and it should work.

**Comment by kevineger** [comment]
Thanks @LukeNZ 

I'm considering just building in RoR instead. The [Ruby API Wrapper](https://github.com/avidw/redd) seems to be well maintained. That way I don't have to muck around with setting up all the endpoints I need (pretty much all of them).

**Comment by kevineger** [comment]
@LukeNZ Actually Luke, how hard do you think it'd be to get things up and running with full OAuth2 support from what you currently have? Looks like you are just missing endpoints and [Token Refreshing](https://github.com/reddit/reddit/wiki/OAuth2#refreshing-the-token)?

**Comment by LukeNZ** [comment]
Hey Kevin,

I believe it's just missing Token Refreshing, endpoints, and setting a user-agent correctly. I was really hoping to get a more expressive syntax via method chaining where possible, something like:

    `$connection->subreddit('running')->comments();`
    `$connection->user('foo')->friend('bar');

So it wasn't going to map 1-1 with Reddit but slightly improve Reddit's API which I'm not a particular fan of. 

Obviously full OAuth2 is more important.

**Comment by jcleblanc** [comment]
OAuth functionality has been restored, so the endpoints should work with the new edit. This required an SSL version bump.
