### ISSUE TITLE
"403 Forbidden" on simple identity request

### ISSUE THREAD

**Issue by xcodewarrier** [jcleblanc/reddit-php-sdk#63]
The SDK fails on a simple identity request on PHP AppEngine.

```
static $SCOPES = 'identity';

require_once("reddit.php");
$reddit = new reddit(); 
print_r($reddit);
$userData = $reddit->getUser();



403 Forbidden
Request forbidden by administrative rules. 
```

**Comment by rossxwest** [comment]
I am having the exact same issue.

**Comment by jcleblanc** [comment]
I just ran a simple test on a localhost instance (Apache server) as well as an app engine sample application, using the same single identity scope, and had my data returned back correctly. Typically that error response is related to scope issues.

If you are setting the scopes up as above, that may be the issue. You are defining SCOPES before you include reddit.php. reddit.php will include config.php, which includes a definition of the SCOPES variable, so make sure those aren't being overwritten.
